cargo-features=['edition2021']
package= {name= 'cargo', version= '0.0.0', edition= '2021'}
lib= {name= 'cargo', path= 'lib.rs'}
bin= [{name= 'diagnostic', path= 'main.rs'}]

[dependencies]
fehler='*'
serde= {version= '*', features= ['derive']}
serde_json='*'
cargo_metadata='*'
